# Generated by Django 3.2.6 on 2021-08-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_contact_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(default='NOT ENTEREd'),
        ),
    ]
